DISCONNECTED_DISCONNECT_CALLED = 0
DISCONNECTED_UNAUTHORIZED = 1
DISCONNECT_BAD_PROTOCOL = 2
DISCONNECT_MESSAGE_SIZE_LIMIT = 3

CONNECTING_CONNECT_CALLED = 0
CONNECTING_TRANSPORT_CLOSED = 1
CONNECTING_NO_PING = 2
CONNECTING_SUBSCRIBE_TIMEOUT = 3
CONNECTING_UNSUBSCRIBE_ERROR = 4
